package med.voll.api.medico;

public enum Especialidad {
    CARDIOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    GERIATRIA,
    GINECOLOGIA,
    HEMATOLOGIA,
    INFECTOLOGIA,
    MEDICINA_GENERAL,
    NEFROLOGIA,
    NEUMOLOGIA,
    NEUROLOGIA,
    NUTRICION,
    OFTALMOLOGIA,
    ONCOLOGIA,
    ORTOPEDIA,
    OTORRINOLARINGOLOGIA,
    PEDIATRIA,
    PSIQUIATRIA,
    REUMATOLOGIA,
    TRAUMATOLOGIA,
    UROLOGIA
}
