spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${MYSQLPASSWORD}


## spring.datasource.url=jdbc:h2:mem:testdb
##spring.datasource.driverClassName=org.h2.Driver
## spring.datasource.username=sa
##spring.datasource.password=password
## spring.jpa.database-platform=org.hibernate.dialect.H2Dialect