spring:
  profile.active: prod
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: ${MYSQLPASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:123456}